version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.23  # Specify the Go version you are using
    commands:
      - echo Installing dependencies...
      - apt-get update -y
      - apt-get install -y protobuf-compiler

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 651706745547.dkr.ecr.ap-south-1.amazonaws.com
      - echo Setting up environment variables...
      - REPOSITORY_URI=651706745547.dkr.ecr.ap-south-1.amazonaws.com/sample-golang-service
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Compiling protobuf files...
      - make compile_protos
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"<container-name>","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

cache:
  paths:
    - '/root/.cache/go-build/**/*'
    - '/root/.cache/go-proto/**/*'